baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Blog'
theme = 'anatole'

enableRobotsTXT = true


[params]
title = "Salut, je suis Theo Lejeune"
author = "Theo Lejeune"
description = "IngÃ©nieur DevSecOps, n'hÃ©sitez pas Ã  me contacter"
profilePicture = "https://avatars.githubusercontent.com/u/18557909?v=4"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/th%C3%A9o-lejeune-31b6a1176/"


[[params.socialIcons]]
icon = "fab fa-github"
title = "Github"
url = "https://github.com/th3olee/"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:theolejeune@protonmail.com"

[menu]

  [[menu.main]]
  name = "ğŸ“ Blog" 
  identifier = "ğŸ“ Blog"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "ğŸ’¼ Portfolio"
  weight = 200
  identifier = "ğŸ’¼ Portfolio"
  url = "/portfolio/"

  [[menu.main]]
  name = "ğŸ‘¾ A propos"
  weight = 300
  identifier = "ğŸ‘¾ A propos"
  url = "/about/"

  [[menu.main]]
  name = "ğŸ“« Contacts"
  weight = 400
  identifier = "ğŸ“« Contacts"
  url = "/Contacts/"