baseURL = 'https://www.theolejeune.xyz/'
languageCode = 'en-us'
title = 'Blog'
theme = 'anatole'

enableRobotsTXT = true


[params]
title = "Bonjour, je suis Theo Lejeune"
author = "Theo Lejeune"
description = "IngÃ©nieur DevSecOps, n'hÃ©sitez pas Ã  me contacter"
profilePicture = "/profile.jpeg"
mainSections = []



[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/th%C3%A9o-lejeune-31b6a1176/"


[[params.socialIcons]]
icon = "fab fa-github"
title = "Github"
url = "https://github.com/th3olee/"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:theolejeune@protonmail.com"


[menu]

  [[menu.main]]
  name = "ğŸ  Accueil" 
  identifier = "ğŸ  Accueil"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "ğŸ“ Blog" 
  identifier = "ğŸ“ Blog"
  weight = 200
  url = "/posts"

  [[menu.main]]
  name = "ğŸ’¼ Portfolio"
  weight = 300
  identifier = "ğŸ’¼ Portfolio"
  url = "/portfolio/"

  [[menu.main]]
  name = "ğŸ‘¾ CV"
  weight = 400
  identifier = "ğŸ‘¾ CV"
  url = "/about/"

  [[menu.main]]
  name = "ğŸ“« Contacts"
  weight = 500
  identifier = "ğŸ“« Contacts"
  url = "/Contacts/"
